version: '3'
services:
  # grafana:
  #   image: grafana/grafana
  #   environment:
  #     - GF_INSTALL_PLUGINS=grafana-piechart-panel,jdbranham-diagram-panel,grafana-clock-panel,grafana-simple-json-datasource
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./grafana:/var/lib/grafana/
  #     - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
  #     - ./provisioning/datasources:/etc/grafana/provisioning/datasources
  #     - ./dashboard-repo:/var/lib/grafana/dashboards
  cassandra:
    image: cassandra:latest
    ports:
      - "7000:7000"
      - "9042:9042"
    volumes:
      - ./cassandra:/var/lib/cassandra
  bg_init:
    build:
      context: ./
      dockerfile: ./dockerfiles/biggraphite-init.dockerfile
    image: my_bg_init:latest
    volumes:
      - ./bg_init:/bg_init
      - ./shared:/shared
      - ./biggraphite:/biggraphite
    depends_on:
      - cassandra
  bg_carbon:
    build:
      context: ./
      dockerfile: ./dockerfiles/biggraphite-carbon.dockerfile
    image: my_bg_carbon:latest
    depends_on:
      - cassandra
    ports:
      - "2003:2003"
    volumes:
      - ./biggraphite:/opt/graphite/conf
      - ./shared:/shared
  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
  bg_nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./ginx:/etc/nginx
  #bg_graphite:
  #  image:
  #  ports:
  #    - "8080:8080"
  #  depends_on:
  #    - bg_nginx
  #    - bg_carbon
  #    - memcached
